
import "./globals.css";
import { Inter } from "next/font/google";
import { CityContextProvider } from "@/context/CityContext";
import AuthContextProvider, { AuthContext } from "@/context/AuthContext";
import InstitutionContextProvider from "@/context/InstitutionContext";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <CityContextProvider>
            <InstitutionContextProvider>
              {children}
            </InstitutionContextProvider>
          </CityContextProvider>
        </AuthContextProvider>


      </body>
    </html>
  );
}
